//! `scraped-lang`: inspect languages generated by the engine.
//!
//! All I/O lives here; the engine itself stays pure so it can run in a
//! browser later.

use std::process::ExitCode;

use scraped_lang::corpus::Corpus;
use scraped_lang::sheet::GrammarSheet;
use scraped_lang::Language;

const USAGE: &str = "\
usage:
  scraped-lang --seed N corpus [--count 40] [--json] [--spoil]
  scraped-lang --seed N grammar --spoil [--json]

  --seed N    language seed (any unsigned 64-bit number)
  --count K   number of inscriptions (default 40)
  --json      structured output
  --spoil     include ground truth: glosses, meanings, the grammar";

#[derive(Debug, PartialEq)]
enum Command {
    Corpus,
    Grammar,
}

#[derive(Debug, PartialEq)]
struct Args {
    seed: u64,
    command: Command,
    count: u32,
    json: bool,
    spoil: bool,
}

fn parse(args: &[String]) -> Result<Args, String> {
    let mut seed = None;
    let mut command = None;
    let mut count = 40;
    let mut json = false;
    let mut spoil = false;
    let mut it = args.iter();
    while let Some(a) = it.next() {
        let mut value = |name: &str| {
            it.next()
                .ok_or_else(|| format!("{name} needs a value"))
                .cloned()
        };
        match a.as_str() {
            "--seed" => {
                let v = value("--seed")?;
                seed = Some(v.parse().map_err(|_| format!("bad seed: {v}"))?);
            }
            "--count" => {
                let v = value("--count")?;
                count = v.parse().map_err(|_| format!("bad count: {v}"))?;
            }
            "--json" => json = true,
            "--spoil" => spoil = true,
            "corpus" if command.is_none() => command = Some(Command::Corpus),
            "grammar" if command.is_none() => command = Some(Command::Grammar),
            other => return Err(format!("unexpected argument: {other}")),
        }
    }
    Ok(Args {
        seed: seed.ok_or("missing --seed")?,
        command: command.ok_or("missing command: corpus or grammar")?,
        count,
        json,
        spoil,
    })
}

fn run(args: &Args) -> Result<String, String> {
    let lang = Language::generate(args.seed);
    match args.command {
        Command::Corpus => {
            let corpus = Corpus::generate(&lang, args.count);
            Ok(if args.json {
                pretty(&corpus.to_json(args.spoil))
            } else {
                corpus.to_text(args.spoil)
            })
        }
        Command::Grammar => {
            if !args.spoil {
                return Err("the grammar sheet is all spoilers; pass --spoil to see it".to_string());
            }
            let sheet = GrammarSheet::new(&lang);
            Ok(if args.json {
                pretty(&serde_json::to_value(&sheet).expect("sheet serialises"))
            } else {
                sheet.to_text()
            })
        }
    }
}

fn pretty(v: &serde_json::Value) -> String {
    let mut s = serde_json::to_string_pretty(v).expect("json serialises");
    s.push('\n');
    s
}

fn main() -> ExitCode {
    let raw: Vec<String> = std::env::args().skip(1).collect();
    if raw.is_empty() || raw.iter().any(|a| a == "-h" || a == "--help") {
        println!("{USAGE}");
        return ExitCode::SUCCESS;
    }
    match parse(&raw).and_then(|a| run(&a)) {
        Ok(out) => {
            print!("{out}");
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("error: {e}\n\n{USAGE}");
            ExitCode::FAILURE
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn args(s: &str) -> Vec<String> {
        s.split_whitespace().map(String::from).collect()
    }

    #[test]
    fn parses_corpus() {
        let a = parse(&args("--seed 7 corpus --count 5 --json --spoil")).unwrap();
        assert_eq!(
            a,
            Args {
                seed: 7,
                command: Command::Corpus,
                count: 5,
                json: true,
                spoil: true
            }
        );
    }

    #[test]
    fn flags_in_any_order() {
        let a = parse(&args("grammar --spoil --seed 3")).unwrap();
        assert_eq!(a.command, Command::Grammar);
        assert_eq!(a.seed, 3);
        assert_eq!(a.count, 40);
    }

    #[test]
    fn rejects_bad_input() {
        assert!(parse(&args("corpus")).is_err());
        assert!(parse(&args("--seed x corpus")).is_err());
        assert!(parse(&args("--seed 1")).is_err());
        assert!(parse(&args("--seed 1 corpus --bogus")).is_err());
    }

    #[test]
    fn grammar_requires_spoil() {
        let a = parse(&args("--seed 1 grammar")).unwrap();
        assert!(run(&a).is_err());
    }

    #[test]
    fn corpus_without_spoil_has_no_glosses() {
        let a = parse(&args("--seed 1 corpus --count 10")).unwrap();
        let out = run(&a).unwrap();
        assert_eq!(out.lines().count(), 10);
        assert!(!out.contains('-'), "no morph boundaries leak: {out}");
        let a = parse(&args("--seed 1 corpus --count 10 --json")).unwrap();
        let out = run(&a).unwrap();
        assert!(!out.contains("gloss") && !out.contains("meaning"));
    }
}
